name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Inject API Key into JavaScript
              uses: jacobtomlinson/gha-find-replace@v2
              with:
                  find: "API_KEY_PLACEHOLDER"
                  replace: ${{ secrets.API_KEY }}
                  include: script.js

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./
